// <auto-generated />
using System;
using ITLATv.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITLATv.Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITLATv.Database.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("ITLATv.Database.Models.Producter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productora", (string)null);
                });

            modelBuilder.Entity("ITLATv.Database.Models.Serie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryGenderId")
                        .HasColumnType("int");

                    b.Property<int>("ProducterId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondaryGenderId")
                        .HasColumnType("int");

                    b.Property<string>("VideoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryGenderId");

                    b.HasIndex("ProducterId");

                    b.HasIndex("SecondaryGenderId");

                    b.ToTable("Serie", (string)null);
                });

            modelBuilder.Entity("ITLATv.Database.Models.Serie", b =>
                {
                    b.HasOne("ITLATv.Database.Models.Gender", "PrimaryGender")
                        .WithMany("Series")
                        .HasForeignKey("PrimaryGenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITLATv.Database.Models.Producter", "Producter")
                        .WithMany("Series")
                        .HasForeignKey("ProducterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITLATv.Database.Models.Gender", "SecondaryGender")
                        .WithMany()
                        .HasForeignKey("SecondaryGenderId");

                    b.Navigation("PrimaryGender");

                    b.Navigation("Producter");

                    b.Navigation("SecondaryGender");
                });

            modelBuilder.Entity("ITLATv.Database.Models.Gender", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("ITLATv.Database.Models.Producter", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
